apiVersion: "v1"
kind: "Service"
metadata:
  name: "myapp-service"
  namespace: "default"
  labels:
    run: "myapp"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  selector:
    run: "myapp"
  type: "LoadBalancer"
  loadBalancerIP: "35.232.110.38"

